---
# tasks file for anisble-role-vault

# Variable setup.
- include: variables.yml

# Prerequisites Setup
- include: pre_install.yml

# Setup/install tasks.
- include: install.yml

# Typically configuration that should happen before service start
- include: pre_configure.yml

# Start/ restrat the service as needed
- include: flush.yml

# Special post_configuration. Only needed once per data backend
- include: initialize.yml

#Token variables include
- include: variables.yml

# Read in any secrets that are needed for configuration
- include_vars: tokens.yml

# FLush any handlers
- include: flush.yml

# Typically configuration that should happen before service start
- include: post_configure.yml

## Cleanup
#- include: cleanup.yml
